### ISSUE TITLE
[Feature Request]: Refine CDI implementation

### ISSUE THREAD

**Issue by wadhwamatic** [WFP-VAM/prism-app#1181]
### Provide a clear and concise description of what you want to happen.

The implementation of CDI needs some refinement both within PRISM and on the hip service side.

1. We should consider how we can improve performance. Can we prefetch the latest CDI?
2. If an input layer for the CDI is not published via HDC's WMS, we can't display it within the layer drop down (see screenshot below). Rather than not show it, we could simply display the layer as a text field without a layer toggle. This would require a `title` in the `input_layers` configuration in PRISM
1. I think we should have two types of CDI layers in PRISM – `monthly` and `seasonal` (TBC before implementing)
a. If seasonal, the configuration in layers.json should require the start of each season and end of each season as parameters. For example, `s1_start` = 1-January; `s1_end` = 31-March; `s2_start` = 1-April; `s2_end` = 30-June; etc.
b. The user’s timeline selection should determine which dates are used in the CDI request. For example, if the user selects CDI for today, 2-April, the seasonal request should include the latest available season, which in this example would be season 1 (Jan-March). 
c. If monthly, we simply have CDI refer to the full calendar month. In the case of a user selecting 2-April, we should show CDI for the month March
3. There’s no map interaction with the CDI layer. Ideally, a user should be able to see the CDI value in the tooltip when they click on a pixel.
4. From what I understand, the aggregation options within each input layer should be implicitly derived on the hip service side instead of expected as parameters in the PRISM configuration. @paololucchino - can you confirm if this is correct and if we can adjust on the hip service?
5. Future to do – I think we should also add an option to aggregate CDI pixel results and get the mean value per admin area. This will require zonal stats to be implemented within the hip service, and for the PRISM frontend to be modified to send a boundary file in the request and to map the response accordingly.

As mentioned in the 2nd bullet point above, the PRISM interface only shows SPI as an `input_layer` because other input layers are not available through HDC
<img width="495" alt="Screenshot 2024-04-02 at 16 59 19" src="https://github.com/WFP-VAM/prism-app/assets/3343536/785aa2de-4fae-4502-bfc9-c40835b35ab1">

**Comment by lowriech** [comment]
Some quick thoughts, mostly driven on my not contributing to PRISM previously:
1. I feel like we should just figure out how to move CDI into HDC.  HIP doesn't meaningfully have a storage solution AFAIK, which puts us in a world of relying on caching and pre-fetching.  We had discussed having CDI in HDC once we had a config that we were happy with, thoughts?
2. Probably easy enough, although I don't have any idea how the PRISM layer selection works.  @ericboucher could you give some quick input on what files need to be edited to show non-selectable layers?  Seems like editing `layers.json`, adding a new type and importing in `layer-data.ts`, and modifying the Left Panel to consume appropriately?  What am I missing?
3. At the moment, it appears `begin` in the request appears to be hardcoded to `2023-12-01`, this should move with the time selection for monthly (for now, until we decide on a seasonal switch).  @ericboucher could you give some context on the files to edit here?
4. Getting this into HDC would allow for interaction, yes?
5. This just seems to come down to what our default config is.  At the point that we're not supplying a configuration, it doesn't make sense to me to run this through HIP.  At best, we're just using HIP as a static asset server at that point.
6. Is this what the analysis tab is partially doing?  Some form of zonal stats endpoint makes sense, but seems like we'd get that if it's in HDC.

**Comment by wadhwamatic** [comment]
@lowriech - responses below on the few of your points:

> * I feel like we should just figure out how to move CDI into HDC.  HIP doesn't meaningfully have a storage solution AFAIK, which puts us in a world of relying on caching and pre-fetching.  We had discussed having CDI in HDC once we had a config that we were happy with, thoughts?

An HDC generated CDI is viable for an eventual continent-wide version. But as an example, the Jordan CDI is distinct and we need to support multiple configurable versions of it (sector specific CDIs) which is one of the reasons we've gone down the hip-service route.  

> * Getting this into HDC would allow for interaction, yes?

HDC delivers images to PRISM via WMS and GeoTIFFs via STAC API requests. In the case of CDI, hip returns a geojson with point data converted to hex. Users should be able to click on the hex and see a value in the tooltip. This is a PRISM UI enhancement.

> * This just seems to come down to what our default config is.  At the point that we're not supplying a configuration, it doesn't make sense to me to run this through HIP.  At best, we're just using HIP as a static asset server at that point.

We are supplying an aggregation parameter for each `input_layer` in layers.json and that is sent to the qmulti / hip service request. The options I see as of now are `last_dekad` or `average`. Unless I have missed something major, we're not serving a static asset but rather computing the CDI value on the fly based on the configuration. I must be misunderstanding what you mean here.

> * Is this what the analysis tab is partially doing?  Some form of zonal stats endpoint makes sense, but seems like we'd get that if it's in HDC.

Yes, PRISM's API can run zonal stats, but so can the hip analysis package. We'd want zonal stats run on the CDI result within hip service. HDC doesn't perform zonal stats. If you're referring to the HDC stats API, that is something Valentin has setup for a handful of layers, not as an on-the-fly calculation.

**Comment by paololucchino** [comment]
Hi @wadhwamatic and @lowriech,

Adding some thoughts on the points where I am familiar with the issue.

On 1:

- Agree that a global/continent wide CDI will eventually come from HDC. Until then, and even then for any _custom_ CDI, hip-service is were the results would come from. 
- Caching has taken us a long way already, where once results are cached, the response is ~8s. This remaining latency is due to compute, and could be addressed by using a larger instance (currently we only have 2 CPUs). 
- Initial caching is still way too slow (4min), and this currently needs to be re-run every time the instance is restarted. If the [cache location were in s3](https://github.com/WFP-VAM/hip-service/pull/9#issuecomment-1966065054), then the 4min would only ever happen to the very first user requesting a CDI each dekad. [Caching in s3](https://github.com/WFP-VAM/hip-analysis/issues/4) would be a foundational feature in hip-analysis which benefits to any downstream application. This would perhaps already take us to an acceptable user experience.
- For the perfect UX, we could set up an automated ping of the endpoint each dekad, so no human user would ever need to wait the 4min.

On 3: 
- There are a few permutations on how to deal with the time aggregation of a CDI, and there isn't yet a consensus about this from the subject matter experts, though hopefully this should come soon. That said, some comments:
- `monthly` can be on a rolling month basis i.e. a value for the CDI over a month to dekad X, with X not having to be the end of the month.
- 'seasonal' has two variants. One with user-defined season dates, like @wadhwamatic describes. The other internally using the definition of season we have for each pixel. This latter one would only require the user to specify the time T date, and the CDI would be automatically be calculated for from the pixel level start of season to time T.

On 5:
- Yes this was poor design on the hip-analysis end. Both the `aggregation` and `invert` argument are deterministic given a chosen indicator. So PRISM should be able to omit them and [hip-analysis would provide suitable default for each key.](https://github.com/WFP-VAM/hip-analysis/issues/74)

On 6:
- hdc stats-api is for admin boundries (as stored in hdc) and for a limited set of variables. The feature here would be to allow any data loaded in PRISM to be aggregated at any user requested geometry. The hdc development roadmap includes a feature to do extractions on arbitrary geometries but the timescales for it are not defined, and would only available for hdc variables, and perhaps even a subset of them. hip-analysis has this functionality already, and could expose it for any indicator in its catalogue, as well as for any result that is derived from on the fly computation. Implementation is possible, resourcing, timescales etc to be discussed though.

**Comment by wadhwamatic** [comment]
Thanks @paololucchino. I think Chris should have the necessary inputs from us with these clarifications. 

@ericboucher - there are couple of questions from @lowriech to you here: https://github.com/WFP-VAM/prism-app/issues/1181#issuecomment-2035747563. Hoping with those provided, Chris can move forward.

**Comment by wadhwamatic** [comment]
> * For the perfect UX, we could set up an automated ping of the endpoint each dekad, so no human user would ever need to wait the 4min.

@ericboucher suggested the same thing. Eric, can you give details on how you envision this being implemented?

**Comment by ericboucher** [comment]
@lowriech 

2. Have a look at `getCompositeLayers` and change it to return "fake" layers for non-existing layers. Maybe with type `disabled`. Then adapt SwitchItem accordingly

3. The initial requirement for Jordan was seasonal, but if you want to change that to monthly you should be able to update the logic fairly easily in `/src/context/layers/composite_data.ts`
