### ISSUE TITLE
Need a layout option that better suits 'portrait' orientation

### ISSUE THREAD

**Issue by wadhwamatic** [WFP-VAM/prism-app#140]
Many of our upcoming deployments are in countries that reach further north to south than east to west. Examples include Myanmar and Mozambique. We need to develop a configuration option that will easily support presenting the map display with a portrait orientation, and reorganizing the navigation to the left of the screen, vertically. I'll add some mockups here when time allows. If anyone has thoughts to share, please add in the comments!

**Comment by dubwalla** [comment]
Let's discuss @erwagasore

**Comment by erwagasore** [comment]
## Portrait Screens

These are potential screen design for a PRISM optimized for `Portrait` countries. While doing these screens I based on these foundations:
- Incremental changes, thus didn't do radical changes which tends not to be implemented.
- Minimal / Contractible components, if a component is not being used it should be out of the way. 
- Grouping by relationship

Even-though screens below are meant for `portrait` countries with small tweaks the same screens would easily serve with `landscape` countries.

### Portrait Changes
#### Timeline
The timeline is relatively the same with our current portrait, we have it in portrait mode. The area showing the `selectedDate` no longer show the date only shows the icon. When clicked it would show the `date selector`.

#### Map View
The map view by default is magnified beyond the natural borders. This was intentional to showcase the idea of having
two elements while configuring the `country_boundaries`. In a nutshell we would have the `fit` and `Idea` bounding box.
With such configuration we will be able to do some panning actions for areas not in view. This is useful for very tall countries.

e.g. configuration json
```json
...
"country-boundaries": {
  "fit": "bboxElement",
  "ideal": "zoomedInBboxElement",
},
...
```

#### Zoom to Fit and Panning Controls
Since the map view start in `Ideal` zoom level we also show controls to allow the user to pan `upward` or `downward` to areas not visible. We also provide the `zoomToFit` controls when it would automatically show the entire surface area of the country regardless on how small it may appear vis-a-vis the screen real-estate.

#### Right Sidebar
The right sidebar is a more action oriented area. It is composed of `Layers`, `Run Analysis`, and `Create Alert` Panels.
Only one panel is active at a time thus gives room for other map activities. This is also going to be user friendly to have a location where the user know it is `action` based area. Instead of looking left and right.

Below are screens to better preview. @wadhwamatic @ericboucher @Ry-DS @JorgeMartinezG Please share your point of view.

#### Full featured *portrait* screen with `different` right sidebar panels active
![image](https://user-images.githubusercontent.com/1290048/128535978-209ac6dd-6679-4e8f-99e5-bd126849e403.png)

![image](https://user-images.githubusercontent.com/1290048/128539046-a4ed7fcf-6b63-4377-be00-f1b2a4d553a8.png)

![image](https://user-images.githubusercontent.com/1290048/128539100-2194c56f-3c14-4c93-9143-1de6b536df8d.png)

#### Minimal *portrait* screen with all controls contracted in their minimal forms
![image](https://user-images.githubusercontent.com/1290048/128539349-e8ad45b0-4597-4618-83d6-cc905eaaa092.png)

![image](https://user-images.githubusercontent.com/1290048/128539409-c90ff644-3434-4e3d-bcbf-95ee08383f40.png)



####

**Comment by erwagasore** [comment]
@wadhwamatic  Please find the link to an interactive prototype for you to experience the new proposed  user interface for PRISM https://www.figma.com/proto/5aoFmgB7MUffkM79BXbGEO/PRISM-UI-UX-Proposal?node-id=0%3A1&viewport=241%2C48%2C1&scaling=min-zoom&starting-point-node-id=6%3A322
