### ISSUE TITLE
Mask out raster data outside of national boundaries

### ISSUE THREAD

**Issue by wadhwamatic** [WFP-VAM/prism-app#170]
When a user loads a raster hazard layer (such as NDVI), it's easy to lose focus on the area of interest (aka the deployment country). This is especially true in landlocked countries, and countries with complex boundaries. See the examples from Tajikistan below.

<img width="1421" alt="Screen Shot 2021-04-22 at 12 29 24" src="https://user-images.githubusercontent.com/3343536/115775185-65371600-a367-11eb-801a-e4be0d42113d.png">

<img width="1422" alt="Screen Shot 2021-04-22 at 12 29 10" src="https://user-images.githubusercontent.com/3343536/115775204-6e27e780-a367-11eb-93a2-447b0e50e747.png">

We need to explore options to visually keep focus on the area of interest while also recognizing that many hazard layers should be seen in comparison across national borders. We could consider a mechanism that 'greys out' countries outside of the area of interest, or to fully mask data outside of the area of interest. See a relevant tutorial here: https://www.mapbox.com/blog/masking-in-studio-using-high-resolution-administrative-country-polygons

**Comment by dubwalla** [comment]
See also https://github.com/WFP-VAM/prism-frontend/issues/169 relating to configurable style options

**Comment by wadhwamatic** [comment]
@reed1 - this is a follow up to the call we had recently when we discussed masking out other countries. Thanks for looking into that further and suggested some potential solutions

**Comment by ericboucher** [comment]
A simple approach could be to add bounds to the WMS layer so that we limit the tiles we get to the geographic area of interest. This will also make it easier on the servers that we are requesting data from.

It can be as simple as adding this:

```
      <Source
        id={`source-${id}`}
        tileJsonSource={{
          type: 'raster',
          tiles: [
            `${getWMSUrl(baseUrl, serverLayerName, {
              ...additionalQueryParams,
              ...(selectedDate && {
                time: moment(selectedDate).format(DEFAULT_DATE_FORMAT),
              }),
            })}&bbox={bbox-epsg-3857}`,
          ],
          // TODO - create this bound programitically or get from config
          bounds: [103, 11, 106, 15],
          tileSize: 256,
        }}
      />
```

Quick note - we probably want to have bounds covering an area much larger than the country of interest to make sure that we don't have any missing tiles. There might be a formula to derive from the country boundaries, tileSize, and the current zoomLevel

**Comment by ericboucher** [comment]
Also linked to #430 as I think we should keep borders and country names above colors

**Comment by reed1** [comment]
@wadhwamatic here are my findings so far:

1. OpenLayer can do clipping on browser side, I implemented a sample OpenLayer map with ODC layer here: https://odc-clip-idn.surge.sh/

2. There's this mapbox-gl clipping using d3 svg: [Source](https://gist.github.com/enjalot/985de8fcd65d37583949edbf280f2632). I tried here: http://mapbox-clip.surge.sh/ but the map sometimes breaks when zooming in and out

3. I implemented a simple clipping image server, basically proxifying the WMS request and clip the PNG result using rendered GeoJSON on the same resolution and bounding box: 
[IDN Clipped Layers](https://prism-dev-clip.wfpidn.link/?hazardLayerId=rainfall_agg_1month&date=2022-04-11)
[IDN Original Layers](https://prism-dev.wfpidn.link/?hazardLayerId=rainfall_agg_1month&date=2022-04-11)
The downside is that it's another service to run and will add additional time proxifying the image request, it can be minimized if the service run on the same network with WMS server

4. Recent version of GeoServer has this [clip parameter](https://docs.geoserver.org/latest/en/user/services/wms/vendor.html#clip) feature. I tried it on ODC but it doesn't seem to support it. But this clip polygon also limited because URL 2,048 character limitation.

Temporarily, we'll use solution 3 (using clipping image server) for IDN prism installation until better solution found

**Comment by wadhwamatic** [comment]
Thanks @reed1. Can you please put your code for the implementation of option 3 somewhere where I can have @valpesendorfer have a look? We wouldn't want to introduce another service for this but the option we could explore is for ODC support. Valentin is actively engaged with the ODC community and might have some info on raster masking.

**Comment by reed1** [comment]
@wadhwamatic, it's here [clip.zip](https://github.com/WFP-VAM/prism-frontend/files/8504186/clip.zip). Bunch of scripts clumped together (js, bash, pyhon, gdal_ commands,..). It should be possible to unify those to a python file, but it's not our focus right now. 

the base_url for layer in PRISM will be changed from `https://odc.ovio.org/` to `https://odcclip.wfpidn.link/indonesia/odc.ovio.org/` where `odcclip.wfpidn.link` is where the code is hosted and `/indonesia/` path means it's using `mask/indonesia.geojson` file.
