### ISSUE TITLE
Propose new UX for date selection

### ISSUE THREAD

**Issue by ericboucher** [WFP-VAM/prism-app#19]
The current date selection implementation is not ideal. Let's propose improvements from a UX and UI perspective.

*Current implementation*

<img width="1642" alt="Screen Shot 2020-04-09 at 5 45 31 PM" src="https://user-images.githubusercontent.com/16843267/78952289-ef2c7d80-7a89-11ea-91cd-0c12975a1e8d.png">

*Context*
Layers can have data available daily, once per month or every 10 days. We can only select dated layer at a time.

**Comment by laveesh** [comment]
We have got two new designs for the date picker. 
![Design 1](https://user-images.githubusercontent.com/31915056/84622545-e4172300-aefa-11ea-8425-757ce364b499.png)
![Design 2](https://user-images.githubusercontent.com/31915056/84622514-d366ad00-aefa-11ea-84ef-a072b16a0242.png)

**Comment by SimplyBallistic** [comment]
**UX Behind both designs**
 - We wanted to closely match the feel of Material UI, which is why we believe replacing the old date picker would be best here. 
 - Both designs we posted more closely match the design of Material UI while also allowing easy styling via CSS. 
 - We removed the bottom bar entirely as we believed it introduced unneeded complexity to the date selection. Moving everything to one dialog makes the process smoother.
 - The selector was moved to the top left to make it symmetrical with the Legend.

**UX Behind Design 1**
 - Design 1 aims to make the process centered to the user by taking the whole screen. 
 - The selector is part of Material UI/picker making it the closest match to PRISM's design. 
 - There are arrow buttons on the left and right so you can easily jump between possible dates instead of months, which makes more sense to the user.
 - While not shown here, we can disable dates so the user can see exactly which years and dates are available for them to choose from.

**UX Behind Design 2**
 - Design 2 instead moves everything from the old design to the top right corner.
 - There is instead a month drop down to allow you to see exactly which months are available to choose from. 
 - There is an non-intrusive overlay instead of taking the center of the page.

These designs are more so to provide ideas for the final solution. If you have a plan to mix and match both designs let us know!

**Comment by SimplyBallistic** [comment]
**Other considerations**
We could also look into restyling the legend button so it looks more inline with Material UI, or converting it to a dropdown too.

**Comment by dubwalla** [comment]
Thanks Ryan and Laveesh for taking this on - really appreciated! Some additional context:

- The data layers displayed in the maps have a strong time dimension to them. They show the progression of climate conditions which users monitor over time. So the ability to quickly be able to advance / step back in time is important. For example, I might want to see how a drought is progressing over a 3 month period by clicking ahead and visualizing month by month, i.e. quickly skip from June, July, to August. The bottom bar was useful for that, but any proposed ideas to improve how a user can easily skip ahead and backwards in time would be great.
- Users also want the ability go to a specific point in time. For example, I might want to see what the map shows for flooded areas in 08-17-2017. The calendar picker solves that well.
- The map can load multiple layers at a time and each layer could potentially have a separate time period. For example, many of the layers are derived from satellite data. Some of those satellite products have a 10-day interval, others 1-month, and down the road others could have 5-day. We don't really have a good solution for what should happen when a user selects a date from the bottom bar or calendar picker and multiple layers are active that each have their own date intervals. This is a tough one and I haven't really seen a solution out there that does this elegantly. Any input would be great!

For an example of how complicated things can get, have a look at this NASA application:
https://worldview.earthdata.nasa.gov/

**Comment by ericboucher** [comment]
As @dubwalla pointed out, it could be interesting to see the "range" that the data is actually covering. We currently have a `date_interval` setting in the layers.json that could be used to do that.

Eg. with a date picker a bit more similar to the old version - https://vampire.idn.wfp.org/, instead of a single tick, we could have a range.

**Comment by SimplyBallistic** [comment]
thanks for the links, helped give a much clearer image of what needs to be achieved. 
I really like how vampire implemented its date picker, we could use its design as a jumping board for something newer.
A few ideas that could work with Vampire:
- It would be pretty neat if we had a 'play' button in the date picker. If we cache all the data beforehand, we could switch between dates chronologically at a set speed so users can see how something changes over time. A range system could be built into this as well so you can pick a starting date and ending date.

**Comment by laveesh** [comment]
As pointed in the third point by @dubwalla that are different dates for the different layers of the data. 

So, I have a suggestion that we can have the functionality to select the date for the particular layer (i.e. selected layer). It means we are not going to make date selected to apply globally, i.e. on every layer. Instead, we can have datepicker for every layer selected and showing the date applicable for that particular layer for which the date picker is opened.

**Comment by dubwalla** [comment]
> It would be pretty neat if we had a 'play' button in the date picker

@SimplyBallistic - A play feature is definitely a nice to have. I'm interested to hear how achievable this is for rasters that could be a bit heavy size-wise. Not a priority at the moment, but great suggestion for future work.

@laveesh - I'd consider the priority to be an approach that allows a user to navigate through time from without having to individually pick dates but to have awareness of what is happening in terms of dates when multiple layers are active.

As an example, Layer A has daily data, and Layer B has a 10-day interval. A is loaded first, then B. If a user starts scrolling back in time, I think a 10-day interval is what should be expected since B was the last thing they opted to see. But the user should have some way to know exactly which dates are being displayed for each layer. If they want to switch back to daily, they need a want to make Layer A 'active' in terms of time navigation. 

Hoping this stimulates some ideas for UX solutions but happy to find time for a call to discuss too.

**Comment by hav142** [comment]
Hi all,

I’m trying to refactor the date picker to a timeline slider like the image below

![image](https://user-images.githubusercontent.com/25983260/102471973-65a56480-4088-11eb-89c0-9bb4362facee.png)

Currently available features/mechanisms are:
- User can drag the timeline and pointer separately
- Show date information tool-tip when hovering the mouse into slider
- Show available dates with a blue line to distinguish them from the empty dates
- Automatically select the closest date when user drags the pointer over an empty date
- Snap the pointer back to the previous position if no date is available
- Center the timeline automatically when user select a date outside the displayed timeline (from the date picker button on the left) so that the pointer will always be visible
- Add next/prev button to increase / decrease the date to the closest available date

The timeline slider is currently available in branch: [idn_dev](https://github.com/WFP-VAM/prism-frontend/tree/idn_dev/), and there are still some things that need to be fixed regarding some behaviors such as when a user moves from one map layer to another.

Please let me know If you have any suggestions about this timeline slider.

**Comment by dubwalla** [comment]
Thanks for this proposal. I like the slider approach.  The functionality as new layers are activated is the primary concern as we test this. Please send an update with a PR when its ready for testing

**Comment by mwarizmiwafiq** [comment]
Thanks mas @hav142 for the update. 

I have some input:
- Could we select the date in timeline just by click in the date, not by shift the cursor?

Dear all, how do you think the best way to handle "multiple" layers activated? For example in the old version of VAMPIRE, we have "button" to choose which "action" are activated during the timeline.

![image](https://user-images.githubusercontent.com/22732104/102595083-a618e700-4149-11eb-9895-0d9d5ad2e01f.png)

And to reply @dubwalla comment, how do you think the best way to make the PR to feature changes? Our limitation is that we can't directly make PR to master due to differences in layer config file. Should we made a dedicated branch from master specific for each features? Or is there a way to create PR for only specific files?

**Comment by dubwalla** [comment]
> And to reply @dubwalla comment, how do you think the best way to make the PR to feature changes? Our limitation is that we can't directly make PR to master due to differences in layer config file. Should we made a dedicated branch from master specific for each features? Or is there a way to create PR for only specific files?

Once we have a working version ready to test, we can then use the PR to update the code which has changed and manage differences directly in GitHub. I don't think differences in config files should make any difference. I.e., the change for the date feature should not behave any different in Mongolia than Indonesia

**Comment by wadhwamatic** [comment]
Closing out this old issue which was resolved via https://github.com/WFP-VAM/prism-app/pull/139
