### ISSUE TITLE
EWS-1294 warning level is incorrect for Cambodia

### ISSUE THREAD

**Issue by wadhwamatic** [WFP-VAM/prism-app#570]
There's an error in the EWS 1294 which leads to an incorrect warning state. In this example, you can see that the river level has exceeded the 'warning' level, but we still display the 'normal' symbology. The symbology should be based on the max value for the day. 

<img width="1440" alt="Screen Shot 2022-09-29 at 10 06 54" src="https://user-images.githubusercontent.com/3343536/193096214-db5abd7a-2f67-484f-a1c4-750e130636e0.png">

**Comment by wadhwamatic** [comment]
@JorgeMartinezG - maybe this is a timezone issue?

**Comment by wadhwamatic** [comment]
@JorgeMartinezG - It seems that we only captured 3 of the 4 possible states for the EWS levels. There should be 4 levels: normal, watch, warning, severe warning. I tried to fix this in PR https://github.com/WFP-VAM/prism-app/pull/571 but that should be reviewed!

**Comment by JorgeMartinezG** [comment]
@wadhwamatic checked the trigger level and your commit is fine. I pushed another change which defines the new range of dates to query to the new API. However, it would be good to get from their side the api docs, since the query parameters that they use within their website differs from the ones using right now. Also, there is no specification about which timezone and date formats the api accepts.
