### ISSUE TITLE
Display raster median in tooltips

### ISSUE THREAD

**Issue by ericboucher** [WFP-VAM/prism-app#64]
When clicking on an admin boundary when a WMS raster is selected, I would like the median value to be displayed in the tooltip.

**Comment by bencpeters** [comment]
Implementation note:

2 ways to do this:

1. We implement WCS layers as suggested in a comment in #43.
  This gives us the most flexibility to do data transforms, manipulations, define legends dynamically on the fly, etc. This will make the load time more similar to Impact layers though.

1. We could dynamically fetch data just for the district on click. This has the advantage of doing the loading only on demand, and a much smaller memory/load time footprint (since we only have to load a relatively small district's worth of data), but it would mean a lot more individual requests to the geo servers if this feature was used a lot, and it would mean that the tooltip would have a bit of loading delay.

**Comment by bencpeters** [comment]
Note: with the new API in #80, we probably want to implement this with an API call, rather than either 1) or 2).

**Comment by ericboucher** [comment]
Should we add an id filter on the API, so that we can calculate this info for a specific zone?

**Comment by dubwalla** [comment]
A reminder that we also need to display raster stats in a table view as well, not just in the tooltip. The table view would show a value for each admin area

**Comment by ericboucher** [comment]
@bencpeters @dubwalla we could trigger the zonal stats for rasters that have a WCS config in the background.

This behavior could be "shut off" either through the config.json or also through a toggle in the frontend?

Noting that the faster the API will be, the more seamless this would become

**Comment by wadhwamatic** [comment]
Covered more practically with the options we have immediately available here: https://github.com/WFP-VAM/prism-app/issues/1150
