### ISSUE TITLE
Unused components

### ISSUE THREAD

**Issue by ericboucher** [WFP-VAM/prism-app#769]
### What happened?

I noticed that a few components are unused after the switch to ux-revamp, using `yarn ts-prune | grep -v 'used in module'`

In particular:
- AdminLevelDataDownloadButton.tsx
- StacRasterDownloadButton.tsx
- exposedPopulationAnalysis.tsx

Is this expected? Did we lose this functionalities or did they simply get revamped into other components?

Also, are we still using the `DataViewer` in the new UX?

### Which country / deployment are you running?

All

**Comment by HarryMytilinaios** [comment]
@ericboucher after a thorough digging I saw that the `Legends` components `AdminLevelDataDownloadButton` `StacRasterDownloadButton` `exposedPopulationAnalysis` are not used anymore, not because we lost the functionalities but because they were all revamped and are no longer necessary. Moreover the `DataViewer` was previously the `ChartsPanel`, which is revamped and is no longer necessary, I took the initiative on cleaning up thos components, and will wire the PR.
